services:
  - type: web
    name: ygv-construcciones
    env: python
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py shell -c "exec(open('create_superuser.py').read())"
    startCommand: gunicorn circuitcore.wsgi --bind 0.0.0.0:$PORT
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    staticPublishPath: staticfiles
