services:
  - type: web
    name: ygv-construcciones
    env: python
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py createsuperuser --noinput

    startCommand: gunicorn circuitcore.wsgi:application --bind 0.0.0.0:$PORT
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    staticPublishPath: staticfiles
