# Generated by Django 5.2.2 on 2025-06-10 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_cliente', models.CharField(max_length=15, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.CharField(blank=True, max_length=45, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tipo_pago', models.CharField(blank=True, max_length=45, null=True)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(default='BORRADOR', max_length=45)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ygv.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('valor_unidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ygv.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proyecto', models.CharField(max_length=45)),
                ('plazo_proyecto', models.CharField(blank=True, max_length=45, null=True)),
                ('insumos_sobrantes', models.CharField(blank=True, max_length=45, null=True)),
                ('supervisor_mantenimiento', models.CharField(blank=True, max_length=45, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('disponibilidad_horaria', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion_estimada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ygv.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'tipo_proyecto')},
            },
        ),
        migrations.CreateModel(
            name='EntradaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ingeniero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada_ingeniero', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada_proveedor', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ygv.insumo')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ygv.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(max_length=45)),
                ('partes_involucradas', models.TextField(blank=True, null=True)),
                ('condiciones_pago', models.TextField(blank=True, null=True)),
                ('penalizaciones', models.TextField(blank=True, null=True)),
                ('descripcion_proyecto', models.TextField(blank=True, null=True)),
                ('modificaciones', models.TextField(blank=True, null=True)),
                ('garantias_seguros', models.TextField(blank=True, null=True)),
                ('doc_adjunta', models.TextField(blank=True, null=True)),
                ('estado_contrato', models.CharField(max_length=45)),
                ('ingeniero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_ingeniero', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_proveedor', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_usuario', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ygv.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('nro_identificacion', models.CharField(max_length=45, unique=True)),
                ('rol', models.CharField(blank=True, max_length=45, null=True)),
                ('dias_trabajados', models.IntegerField(default=0)),
                ('costo_por_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuentos_prestamo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('especializacion', models.CharField(blank=True, max_length=45, null=True)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ygv.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ygv.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
