# Generated by Django 5.2.2 on 2025-07-11 05:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cotizacion', 'Cotización'), ('proyecto', 'Proyecto'), ('inventario', 'Inventario')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('urgente', 'Urgente')], max_length=10)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador único')),
                ('contacto', models.CharField(max_length=100, verbose_name='Contacto del cliente')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del cliente')),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del cliente')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('ciudad', models.CharField(choices=[('BOGOTA_DC', 'Bogotá D.C.'), ('MEDELLIN', 'Medellín, Antioquia'), ('GIRARDOT', 'Girardot, Tolima'), ('CALI', 'Cali, Valle del Cauca'), ('BARRANQUILLA', 'Barranquilla, Atlántico')], default='BOGOTA_DC', max_length=45, verbose_name='Ciudad del proyecto')),
                ('direccion_proyecto', models.TextField(blank=True, null=True, verbose_name='Dirección del proyecto')),
                ('tipo_proyecto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de proyecto')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia/Nombre del proyecto')),
                ('tipo_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO_30', 'Crédito 30 días'), ('CREDITO_60', 'Crédito 60 días'), ('CREDITO_90', 'Crédito 90 días')], default='CONTADO', max_length=45, verbose_name='Tipo de pago')),
                ('plazo_entrega', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plazo de entrega')),
                ('validez_oferta', models.CharField(blank=True, default='30 días', max_length=100, null=True, verbose_name='Validez de la oferta')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IVA')),
                ('aplica_iva', models.BooleanField(default=True, verbose_name='Aplica IVA')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('factura_generada', models.BooleanField(default=False, verbose_name='Factura generada')),
                ('numero_factura', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de factura')),
                ('fecha_factura', models.DateField(blank=True, null=True, verbose_name='Fecha de facturación')),
                ('pdf_factura', models.FileField(blank=True, null=True, upload_to='facturas/', verbose_name='PDF de factura')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Completada'), ('FACTURADA', 'Facturada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=45, verbose_name='Estado')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones adicionales')),
                ('condiciones', models.TextField(blank=True, default='1. Precios sujetos a cambio sin previo aviso.\n2. Validez de la cotización: 30 días.\n3. Forma de pago: 50% anticipo, 50% contra entrega.', null=True, verbose_name='Condiciones especiales')),
                ('firma_base64', models.TextField(blank=True, null=True, verbose_name='Firma del cliente')),
                ('nombre_firmante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del firmante')),
                ('cargo_firmante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del firmante')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_como_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('ingeniero', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Ingeniero'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Ingeniero asignado')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha'],
                'permissions': [('can_approve_quotation', 'Puede aprobar cotizaciones'), ('can_reject_quotation', 'Puede rechazar cotizaciones'), ('can_generate_invoice', 'Puede generar facturas'), ('can_view_reports', 'Puede ver reportes')],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del trabajo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad')),
                ('unidad_medida', models.CharField(choices=[('M2', 'Metros cuadrados (m²)'), ('ML', 'Metros lineales (ml)'), ('M3', 'Metros cúbicos (m³)'), ('UNIDAD', 'Unidad(es)'), ('HORA', 'Hora(s) de trabajo'), ('DIA', 'Día(s) de trabajo'), ('GALON', 'Galón(es)'), ('KG', 'Kilogramo(s)'), ('LITRO', 'Litro(s)')], default='UNIDAD', max_length=10, verbose_name='Unidad de medida')),
                ('valor_unidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor por unidad')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ygv.cotizacion', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Ítem de cotización',
                'verbose_name_plural': 'Ítems de cotización',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('ingeniero', 'Ingeniero'), ('constructor', 'Constructor'), ('administrador', 'Administrador')], default='cliente', max_length=20)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proyecto', models.CharField(max_length=45)),
                ('plazo_proyecto', models.CharField(blank=True, max_length=45, null=True)),
                ('insumos_sobrantes', models.CharField(blank=True, max_length=45, null=True)),
                ('supervisor_mantenimiento', models.CharField(blank=True, max_length=45, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('disponibilidad_horaria', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion_estimada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ingeniero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada_ingeniero', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada_proveedor', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ygv.insumo')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ygv.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(max_length=45)),
                ('partes_involucradas', models.TextField(blank=True, null=True)),
                ('condiciones_pago', models.TextField(blank=True, null=True)),
                ('penalizaciones', models.TextField(blank=True, null=True)),
                ('descripcion_proyecto', models.TextField(blank=True, null=True)),
                ('modificaciones', models.TextField(blank=True, null=True)),
                ('garantias_seguros', models.TextField(blank=True, null=True)),
                ('doc_adjunta', models.TextField(blank=True, null=True)),
                ('estado_contrato', models.CharField(max_length=45)),
                ('ingeniero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_ingeniero', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_proveedor', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_usuario', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ygv.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ygv.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['estado'], name='ygv_cotizac_estado_bc946c_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['cliente'], name='ygv_cotizac_cliente_792396_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['ingeniero'], name='ygv_cotizac_ingenie_651ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['fecha'], name='ygv_cotizac_fecha_50cec8_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['numero_factura'], name='ygv_cotizac_numero__3982d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proyecto',
            unique_together={('cliente', 'tipo_proyecto')},
        ),
    ]
