# Generated by Django 5.2.2 on 2025-06-11 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ygv', '0005_cotizacion_ingeniero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='administrador',
        ),
    ]
