# Generated by Django 5.2.2 on 2025-06-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygv', '0009_cotizacion_aplica_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionitem',
            name='valor_unidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
