# Generated by Django 5.2.2 on 2025-06-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygv', '0011_perfilusuario_avatar_actividad_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
