# Generated by Django 5.2.2 on 2025-06-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygv', '0012_perfilusuario_direccion_perfilusuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
