# Generated by Django 5.2.2 on 2025-06-18 04:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygv', '0013_cotizacion_motivo_rechazo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha'], 'permissions': [('can_approve_quotation', 'Puede aprobar cotizaciones'), ('can_reject_quotation', 'Puede rechazar cotizaciones')], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='cotizacionitem',
            options={'ordering': ['id'], 'verbose_name': 'Ítem de cotización', 'verbose_name_plural': 'Ítems de cotización'},
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones adicionales'),
        ),
        migrations.AddField(
            model_name='cotizacionitem',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas adicionales'),
        ),
        migrations.AddField(
            model_name='cotizacionitem',
            name='unidad_medida',
            field=models.CharField(choices=[('M2', 'Metros cuadrados (m²)'), ('ML', 'Metros lineales (ml)'), ('UNIDAD', 'Unidad(es)'), ('HORA', 'Hora(s)'), ('DIA', 'Día(s)')], default='UNIDAD', max_length=10, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='aplica_iva',
            field=models.BooleanField(default=True, verbose_name='Aplica IVA'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ciudad',
            field=models.CharField(choices=[('BOGOTA_DC', 'Bogotá D.C.'), ('MEDELLIN', 'Medellín, Antioquia'), ('GIRARDOT', 'Girardot, Tolima')], default='BOGOTA_DC', max_length=45, verbose_name='Ciudad del proyecto'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_como_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='contacto',
            field=models.CharField(max_length=100, verbose_name='Contacto del cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Completada')], default='BORRADOR', max_length=45, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ingeniero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Ingeniero asignado'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tipo_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO_30', 'Crédito 30 días'), ('CREDITO_60', 'Crédito 60 días'), ('CREDITO_90', 'Crédito 90 días')], default='CONTADO', max_length=45, verbose_name='Tipo de pago'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ygv.cotizacion', verbose_name='Cotización'),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción del trabajo'),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='valor_unidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor por unidad'),
        ),
    ]
