# Generated by Django 5.2.2 on 2025-07-10 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygv', '0015_alter_cotizacionitem_unidad_medida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha'], 'permissions': [('can_approve_quotation', 'Puede aprobar cotizaciones'), ('can_reject_quotation', 'Puede rechazar cotizaciones'), ('can_generate_invoice', 'Puede generar facturas'), ('can_view_reports', 'Puede ver reportes')], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cargo_firmante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del firmante'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='condiciones',
            field=models.TextField(blank=True, default='1. Precios sujetos a cambio sin previo aviso.\n2. Validez de la cotización: 30 días.\n3. Forma de pago: 50% anticipo, 50% contra entrega.', null=True, verbose_name='Condiciones especiales'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='direccion_proyecto',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección del proyecto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del cliente'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='factura_generada',
            field=models.BooleanField(default=False, verbose_name='Factura generada'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de facturación'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='firma_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Firma del cliente'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='nombre_firmante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del firmante'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de factura'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='pdf_factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas/', verbose_name='PDF de factura'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='plazo_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plazo de entrega'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia/Nombre del proyecto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del cliente'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_proyecto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de proyecto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador único'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='validez_oferta',
            field=models.CharField(blank=True, default='30 días', max_length=100, null=True, verbose_name='Validez de la oferta'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ciudad',
            field=models.CharField(choices=[('BOGOTA_DC', 'Bogotá D.C.'), ('MEDELLIN', 'Medellín, Antioquia'), ('GIRARDOT', 'Girardot, Tolima'), ('CALI', 'Cali, Valle del Cauca'), ('BARRANQUILLA', 'Barranquilla, Atlántico')], default='BOGOTA_DC', max_length=45, verbose_name='Ciudad del proyecto'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Completada'), ('FACTURADA', 'Facturada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=45, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ingeniero',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Ingeniero'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Ingeniero asignado'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['estado'], name='ygv_cotizac_estado_bc946c_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['cliente'], name='ygv_cotizac_cliente_792396_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['ingeniero'], name='ygv_cotizac_ingenie_651ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['fecha'], name='ygv_cotizac_fecha_50cec8_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['numero_factura'], name='ygv_cotizac_numero__3982d3_idx'),
        ),
    ]
